version: '3'
services:
  app:
      build:
        context: ../app
        dockerfile: Dockerfile
      volumes:
        - ../app/src/:/home/node/app/src
      environment:
          NODE_ENV: development
      ports:
        - 3000:3000
  database:
    image: mongo
    ports:
      - "27017:27017"
  api:
      build:
        context: ../api
        dockerfile: Dockerfile
      volumes:
        - ../api/src/:/home/node/api/src
      depends_on:
        - database
      environment:
          NODE_ENV: development
      ports:
          - 9090:9090