version: '3'
services:
  app:
      build:
        context: ../app
        dockerfile: Dockerfile
      volumes:
        - ../app/src/:/home/node/app/src
      environment:
          NODE_ENV: development
      ports:
        - 3000:3000
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod --auth

  api:
      build:
        context: ../api
        dockerfile: Dockerfile
      volumes:
        - ../api/src/:/home/node/api/src
      depends_on:
        - database
      links:
        - database
      env_file: .env
      environment:
          NODE_ENV: development
          DB_HOST: "$DB_HOST"
          DB_USER: "$DB_USER"
          DB_PASS: "$DB_PASS"
      ports:
          - 9090:9090